config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do
      resources :tasks
  end
  get "due_today", to: "tasks#index", as: "due_today"

  authenticated :user do
    root "categories#index", as: :authenticated_root
  end

  devise_scope :user do
    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }, uniqueness: {scope: :user_id}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  before_validation :set_default_due_date
  validates :description, presence: true, length: {minimum: 5}
  def set_default_due_date
    self.due_date ||= Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :tasks, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  
  def record_not_found
    redirect_to categories_path, alert: 'record does not exist'
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = current_user.categories
    @due_today = current_user.tasks.where(due_date: Date.today)
  end

  def show
    @tasks = @category.tasks
  end

  def new
    @category = current_user.categories.new
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "New category successfully created."
    else 
      flash.alert = "Error in creating new category."
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to category_path, notice: "Category has been updated successfully."
    else
      flash.alert = "Error in updating category."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, alert: "Category has been deleted successfully."
  end

  private
  
  def category_params
    params.require(:category).permit(:title)
  end

  def set_category
    @category = current_user.categories.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_category, except: [:index]
  before_action :set_task, except: [:index, :new, :create]
  
  def index
    @tasks = current_user.tasks.includes(:category)
    @due_today = @tasks.where(due_date: Date.today)
  end

  def show;end

  def new
    @task = @category.tasks.new
  end

  def create
    @task = @category.tasks.new(task_params)
    if @task.save
      redirect_to category_path(@category), notice: 'Task is successfully created.'
    else
      flash.alert = 'Error in saving new task.'
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to category_task_path(@category, @task), notice: 'Task is successfully updated.'
    else
      flash.alert = "Error in updating category."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    redirect_to category_tasks_path(@category), notice: 'Task is successfully deleted.'
  end
  
  private
  
  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def set_task
    @task = @category.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :due_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category, class: "category-form-wrapper" do |form|%>
    <div class="category-form-field">
        <%= form.label :title, class: "category-form-label" %><br>
        <%= form.text_field :title, class: "category-form-input" %>
        <% if category.errors.full_messages_for(:title).second %>
            <div class="category-form-error">
                <%= category.errors.full_messages_for(:title).second %>
            </div>
        <% end %>
    </div>
    <div class="category-form-actions">
        <%= form.submit "Save", class: "category-submit-button" %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class = "new-category-title">Edit Category <i class="fa-solid fa-pen"></i> </h1>
<%= render 'form', category: @category%>
<%= link_to 'Back', category_path, class: 'home-link-category-new' %>

app/views/categories/index.html.erb
<div class = "index-container">
    <div class="user-email-box">
        <p class = "everyday-nav">📓︎ Everyday</p>
        <p class="user-email-text">✉ <%= current_user.email %></p>
        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "logout-button" %>
    </div>
    <div class = "tasks-categories-wrapper">
        <div class="tasks-wrapper">
            <div class = "task-title-and-bell">
                <h2><%= link_to 'Tasks for Today', due_today_path, class: "section-title" %></h2>
                <%= link_to '🔔︎', due_today_path, class: "notification-bell" %>
            </div>
            <hr>
            <%if @due_today.count.zero?%>
                <p class = " empty-msg" >No task for today! </p>
            <%else%>
                <% @due_today.each do |task| %>
                    <div class="task-item">
                        <%= link_to category_task_path(task.category, task), class: "task-desc"  do %>
                            <span> 📌︎ <%=task.description%> </span>
                        <%end%>
                        <span class="task-date">(<%= task.due_date.to_date %>)</span>
                    </div>
                <% end %>
            <%end%>
        </div>
        <div class="categories-wrapper">
            <div class ="header-category-list-wrapper">
                <h1 class="categories-section-title">Category List</h1>
                <h1><i class="fa-solid fa-rocket"></i></h1>
            </div>
            <hr>
                <div class = "create-button" >
                    <%= link_to "Create a Category", new_category_path%>
                </div>
                <div>
                    <% if @categories.count.zero? %>
                        <p class="empty-msg">No categories yet.</p>
                        <% else %>
                                <% @categories.each do |category| %>
                                        <%= link_to category_path(category), class: "category-list" do %>
                                            <i class="fa-solid fa-rocket"></i>
                                            <span class = "category-item"><%= category.title %></span>
                                        <% end %>
                                <% end %>
                    <% end %>
                </div>
                </div>       
        </div>
    </div>

    
</div>

app/views/categories/new.html.erb
<h1 class = "new-category-title">New Category <i class="fa-solid fa-rocket"></i> </h1>
<%= render 'form', category: @category%>
<%= link_to 'Home', categories_path, class: 'home-link-category-new' %>

app/views/categories/show.html.erb
<div class = "categories-show">
  <h1 class="category-title"><i class="fa-solid fa-rocket"></i> <%= @category.title %></h1>
    <div>
      <%= link_to edit_category_path, class: 'edit-link-button' do %> 
        <i class="fa-solid fa-pen"></i>
      <%end%>
      <%= link_to category_path(@category), class: 'delete-link-button', data: {
                                                                              turbo_method: :delete,
                                                                              turbo_confirm: "Are you sure?"} do %>
        <i class="fa-solid fa-trash-can"></i>
      <%end%>
    </div>
  <div class="task-specific-categories-wrapper">
      <p class ="task-specific-categories-header"><i class="fa-solid fa-list-check"></i> Tasks</p>
        <div>
          <%= link_to new_category_task_path(@category), class: "add-task-button-show" do %>
            <i class="fa-solid fa-plus"></i> Add
          <%end%>
        </div>
      <% @tasks.each do |task| %>
        <div class ="task-specific-categories-links">
          <%= link_to category_task_path(@category, task) do %>
            <p>📌︎ <%= task.description %></p>
            <p class ="task-specific-categories-date">Due Date: <%= task.due_date %> </p>
          <% end %> 
        </div>
      <% end %>
  </div>
</div>
<div>
    <p><%= link_to 'Home', categories_path, class: "home-link-show" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Journal Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" >
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

    <% flash.each do |type, message|%>
    <div class= "flash-notice"> <%= message %> </div>
    <% end %>
 
  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [category, task], class: "task-form-wrapper" do |form| %>
    <div class="task-form-field">
        <%= form.label :task, class: "task-form-label" %><br>
        <%= form.text_field :description, class: "task-form-input" %>
        <% if @task.errors.full_messages_for(:description).second %>
            <div class="task-form-error"><%= @task.errors.full_messages_for(:description).second %></div>
        <% end %>
        <div>
            <%= form.label :due_date, class: "task-form-date-label"  %>
        </div>
        <div>
            <%= form.date_field :due_date, class: "task-form-date"  %>
        </div>
    </div>
    <div class="task-form-actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/tasks/edit.html.erb
<h1 class = "new-category-title">Edit Task</h1>
<%= render 'form', category: @category, task: @task %>
<%= link_to 'Back', category_path(@category), class: 'back-link-tasks-edit' %>

app/views/tasks/index.html.erb
<div class = "tasks-due-today-wrapper">
    <div class = "tasks-and-date-title-wrapper">
        <h2 class= "section-title">Tasks for Today 🔔︎</h2>
        <p class = "date-today-title"><%= Date.today %></p> 
    </div>
    <hr>
    <% if @due_today.count.zero?%>
        <p class = "empty-msg">No tasks for today!</p>
        <% else %>
            <% @due_today.each do |task|%>
            <div class="task-due-today-item">📌︎ <%= task.description%></div>
        <%end%>
    <%end%>
</div>
<div>
    <p><%= link_to 'Home', categories_path, class: "home-link-due-today" %></p>
</div>

app/views/tasks/new.html.erb
<h1 class = "new-category-title">New Task</h1>
<%= render 'form', category: @category, task: @task %>
<%= link_to 'Back', category_path(@category), class: 'back-link-tasks-new' %>

app/views/tasks/show.html.erb
<div class = "task-show-wrapper">
  <p class ="task-specific-categories-header"><i class="fa-solid fa-list-check"></i> Task on "<%=@task.category.title%>"</p>
  <div class ="task-date-wrapper">
    <p class = "task-description-show">📌︎ <%= @task.description %></h1>
    <p class = "task-due-date-show">Due Date:</i> <%= @task.due_date %></p>
  </div>
    <div class = "edit-delete-wrapper-tasks-show" >
      <%= link_to edit_category_task_path(@category, @task), class: 'edit-link-button' do %>
        <i class="fa-solid fa-pen"></i>
      <%end%>
      <%= link_to category_task_path(@category, @task), class: 'delete-link-button', data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } do %>
          <i class="fa-solid fa-trash-can"></i>
      <%end%>
    </div>
</div>
<div>
  <%= link_to 'Home', categories_path, class: "home-link-tasks-show" %>
</div>
<div>
  <%= link_to "Back to '#{@category.title}' ", category_path(@category), class: 'home-link-tasks-show' %>
</div>